---
kind: pipeline
type: docker
name: default-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: get-version
  image: debian:bullseye-slim
  commands:
  - "apt-get update"
  - "APPVERSION=$(apt-cache policy isc-dhcp-server | sed -n -e 's/^.*Candidate: //p' | cut -d'-' -f1 | tr -d '\n')"
  - "echo $APPVERSION,latest > .tags"
- name: build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: linutux/dhcpd
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

trigger:
  branch:
  - master
  event:
  - push
---
kind: signature
hmac: fe480426ea76c57ddb72e55d5625e3a9705d40252ecbd23f672c8c0cb29eb0a3

...
